# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f17735bd4f0690bbfea501d6b78a1bb5dbfdd8fc0942298f1f6cb0e19861a028e559346b0b0a47fd7fd65385ad97613a4d665e1dc9caac83af4774e741ea048

test:
  secret_key_base: 122ae79087b3f8aae52fa2ee120da2dfcd88e6c5ae3ca08dc5acae994c83c9b1ff43ea095fdc2e4150b4f5622ed56ac8d4226a2945a4515d3e15a9279715271e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
